### ISSUE TITLE
Fill container width?

### ISSUE THREAD

**Issue by intelligence** [justin-chu/react-fast-marquee#11]
Hey!

Lovely little marquee, thanks for sharing 🙏 

Sometimes when using marquees there's not enough content to fill the width of whatever container the marquee lives in, would be cool to be able to toggle a "fill" prop so that it automatically duplicates content to fill up the space so it doesn't appear empty before repeating again :)

Good idea?

**Comment by justin-chu** [comment]
Thanks for using it! Actually, I'm aware of this (see issue #7), but unfortunately haven't had the time to implement a fix similar to what you suggested - I'll let you know when I push a fix.
