### ISSUE TITLE
[Feature Request] New directions: up and down?

### ISSUE THREAD

**Issue by mattjis** [justin-chu/react-fast-marquee#14]
Great marquee! Would love to be able to go up and down too.

**Comment by justin-chu** [comment]
Hey @mattjis, good idea! This is something that I may try working on in the future.

**Comment by wowtrxqn** [comment]
> Great marquee! Would love to be able to go and down too.

Would love to be able to go and down too

**Comment by albseb511** [comment]
I think you can just manually rotate the parent box, and individual items can be rotated counter clockwise

**Comment by irtaza9** [comment]
@justin-chu Hey Justin, what is your plan for this PR?

**Comment by justin-chu** [comment]
Added this in 1.5.0 - however, it's currently experimental and may be buggy. Also note that since I've rotated the child elements, if you want to set the marquee's width and height, just swap the values for vertical marquees.
