### ISSUE TITLE
Infinite scroll does not work when Marquee component is within a container with "position: fixed;"

### ISSUE THREAD

**Issue by o2bomb** [justin-chu/react-fast-marquee#21]
Hello there, thanks for all your hard work on this library.

The title basically describes my issue with the Marquee component, where if its parent container has a fixed position, the infinite scroll fails to work. Removing `position: fixed;` from the parent container allows the infinite scroll to work as expected.

It would be nice if infinite scrolling works with `position: fixed;`; I am trying to create a stock-exchange style banner that stays at the top of the screen, at any given point on the page.

Thanks!

**Comment by o2bomb** [comment]
On a separate note, I noticed that my issue is very similar to #7. My markup is also very similar to https://github.com/justin-chu/react-fast-marquee/issues/7#issuecomment-805615128

**Comment by justin-chu** [comment]
Hey @o2bomb, thanks for notifying me! I think I'll be able to fix this by this weekend, so I'll let you know then.

**Comment by justin-chu** [comment]
Fixed in 1.4.0
