### ISSUE TITLE
cycleComplete callback would be nice!

### ISSUE THREAD

**Issue by basiclaser** [justin-chu/react-fast-marquee#24]
I have a list of different Marquee elements, and it would be nice to only have one active at a time. 
to be able to do something like this for example would be great:
```
<Marquee play={activeMarquee === 0} onCycleComplete={handleCycleComplete} > first thing </Marquee>
<Marquee play={activeMarquee === 1} onCycleComplete={handleCycleComplete} > second thing </Marquee>
<Marquee play={activeMarquee === 2} onCycleComplete={handleCycleComplete} > third thing </Marquee>
```

**Comment by michaelschufi** [comment]
I second that. This would also allow for easy pausing after a cycle for a few seconds. This is nice as we can give the user a better hint on where text begins and ends.
