### ISSUE TITLE
no gradient width in React 16-17

### ISSUE THREAD

**Issue by FriendlyNGeeks** [justin-chu/react-fast-marquee#26]
Keeps adding "function(){[native code]}" to the end of the css var

`
    --gradient-color: rgba(255, 255, 255, 1), rgba(255, 255, 255, 0);
    --gradient-width: 100px,function () { [native code] };
`
`
<ReactFastMarquee speed={speed} gradient={gradientBool} gradientColor={gradColor} gradientWidth={gradientWidth}>
`

**Comment by justin-chu** [comment]
Unable to reproduce this issue, closing for now.
