### ISSUE TITLE
Speeds are different based on content long

### ISSUE THREAD

**Issue by ozgrozer** [justin-chu/react-fast-marquee#3]
Even though I'm using same speed, short contents slide faster than long contents.

```jsx
<Marquee speed='100' gradient={false}>
  <div className='text'>FREE SHIPPINGS</div>
</Marquee>

<Marquee speed='100' gradient={false}>
  <div className='text'>FREE SHIPPINGS ON ONLINE ORDERS OF $50 OR MORE</div>
  <div className='text'>FREE SHIPPINGS ON ONLINE ORDERS OF $50 OR MORE</div>
  <div className='text'>FREE SHIPPINGS ON ONLINE ORDERS OF $50 OR MORE</div>
</Marquee>
```

Here's how it looks
https://w3cpi.csb.app/

Source
https://codesandbox.io/s/w3cpi

Preview
https://user-images.githubusercontent.com/651938/108362205-83b45000-7204-11eb-99c8-ebd23bcbebbe.mov

**Comment by justin-chu** [comment]
I've fixed this issue in the latest patch - let me know if it still doesn't work!
