### ISSUE TITLE
Marquee does not scroll after recent version

### ISSUE THREAD

**Issue by g-delmo** [justin-chu/react-fast-marquee#30]
The marquee animation does not play, elements are left in place instead.

This is happening on version `1.3.0`
I downgraded to `1.2.1` and the issue is resolved.

```js
<Marquee>
  <span>One</span>
  <span>Two</span>
  <span>Three</span>
</Marquee>
```

On `1.3.0` (not working):
![image](https://user-images.githubusercontent.com/59506882/147862016-dc70e2b8-f2f7-492f-9dd1-e30ab5ea3a20.png)

On `1.2.1` (working):
![image](https://user-images.githubusercontent.com/59506882/147862030-e7a5172d-4c65-4488-b718-140ba4f80bc8.png)

**Comment by justin-chu** [comment]
Thanks for letting me know, I've reverted one of the changes so version 1.3.1 should now work!

**Comment by g-delmo** [comment]
Yep, it's fixed now 👍
