### ISSUE TITLE
Warning: Maximum update depth exceeded.

### ISSUE THREAD

**Issue by flash716** [justin-chu/react-fast-marquee#32]
I am seeing the following error in the console when using Marquee.

```
react_devtools_backend.js:2430 Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    at Marquee (http://localhost:1212/dist/renderer.dev.js:315289:17)
```

I believe the first `useEffect` (the one that calls `calculateWidth`) should have an empty dependency array. Without it the effect is continually running since `calculateWidth` changes state every time it runs.

Let me know if you would like a PR for this.

**Comment by justin-chu** [comment]
Should be fixed by #48
