### ISSUE TITLE
play on hover and pause on leave behavior

### ISSUE THREAD

**Issue by ed-ateixeira** [justin-chu/react-fast-marquee#33]
I want the following behavior:

- play on hover;
- pause on leave;
- loop just once but it resets when mouse leaves (when loop is set to 1 and it finishes the loop, I can't make it loop again without a rerender).

I've got close to the result but it took me some useStates and it started to get more and more complex. If there's a way for doing this directly from the component it would be super nice!

**Comment by dh-i** [comment]
@ed-ateixeira Seems like you found a way to fix it. I'm trying to achieve the same. 
Can you please share your solution?

**Comment by ed-ateixeira** [comment]
@dh-i actually I gave up the idea. I found another solution for my needs

**Comment by CoryG89** [comment]
@dh-i I was also trying to play on hover and reset on mouse leave. Probably too late for you, but I was able to get it working. Posting my solution for future reference of anyone trying to do similar. This is written in TypeScript, but should be trivial to convert to vanilla JS if desired:


```ts
const MyComponent: React.FC<{text: string}> = ({ text }) => {
    const marqueeRef = useRef(null);
    const [hasFocus, setHasFocus] = useState<boolean>(false);

    const onMouseEnter = () => {
        setHasFocus(true);
    }
    const onMouseLeave = () => {
        setHasFocus(false);

        if (marqueeRef.current) {
            const marqueeContainer = marqueeRef.current as HTMLElement;
            const marqueeChildren = Array.from(marqueeContainer.children) as HTMLElement[];

            // Force a reflow on marquee child nodes to reset animation
            marqueeChildren.forEach((marquee: HTMLElement) => {
                marquee.style.animation = 'none';
                marquee.offsetHeight;
                marquee.style.animation = '';
            });
        }
    }
    
    return (
        <div onMouseEnter={onMouseEnter} onMouseLeave={onMouseLeave}>
            <Marquee play={hasFocus} ref={marqueeRef}>{text}</Marquee>
        </div>
    );
};
```

**Comment by MitchProbst** [comment]
> @dh-i I was also trying to play on hover and reset on mouse leave. Probably too late for you, but I was able to get it working. Posting my solution for future reference of anyone trying to do similar. This is written in TypeScript, but should be trivial to convert to vanilla JS if desired:
> 
> ```tsx
> const MyComponent: React.FC<{text: string}> = ({ text }) => {
>     const marqueeRef = useRef(null);
>     const [hasFocus, setHasFocus] = useState<boolean>(false);
> 
>     const onMouseEnter = () => {
>         setHasFocus(true);
>     };
>     const onMouseLeave = () => {
>         setHasFocus(false);
> 
>         if (marqueeRef.current) {
>             const marqueeContainer = marqueeRef.current as HTMLElement;
>             const marqueeChildren = Array.from(marqueeContainer.children) as HTMLElement[];
> 
>             // Force a reflow on marquee child nodes to reset animation
>             marqueeChildren.forEach((marquee: HTMLElement) => {
>                 marquee.style.animation = 'none';
>                 marquee.offsetHeight;
>                 marquee.style.animation = '';
>             });
>         }
>     };
>     
>     return (
>         <div onMouseEnter={onMouseEnter} onMouseLeave={onMouseLeave}>
>             <Marquee play={hasFocus} ref={marqueeRef}>{text}</Marquee>
>         </div>
>     );
> };
> ```

This worked really well for my use case. Thank you for sharing!

**Comment by MitchProbst** [comment]
@CoryG89 This worked really well for my use case. Thank you for sharing!
