### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by WojtekLipiarz** [justin-chu/react-fast-marquee#38]
Hi, thanks for the great library.
the library only supports: react@"^16.8.0 || ^17.0.0"

pls also support 18
thanks.

**Comment by KhoiUna** [comment]
Please make this work!!!

**Comment by tr1s** [comment]
@justin-chu when I install this package it's not giving me the most up to date version of this repo with your react 18 commit.

can you update the npm package as well?

**Comment by justin-chu** [comment]
@tr1s Sorry, updated and published now
