### ISSUE TITLE
`console.log`s in consuming apps.

### ISSUE THREAD

**Issue by david-buck** [justin-chu/react-fast-marquee#4]
In the package installed via npm, there are multiple `console.log` calls on load and resize.

It would be preferable if these weren't present, or at least off by default.

![image](https://user-images.githubusercontent.com/5119820/108491928-69b06580-7309-11eb-804e-f056ada24c09.png)

**Comment by justin-chu** [comment]
Thanks for letting me know! I accidentally published some debug `console.log`s - they should be removed now in the latest patch.
