### ISSUE TITLE
[Feature Request] Vertical marquee

### ISSUE THREAD

**Issue by joeyz11** [justin-chu/react-fast-marquee#43]
I would love to see a vertical marquee. Perhaps changing flex-direction and translation direction?

**Comment by jasonchanhk** [comment]
Looking for the same features and found this package, we should try to contribute to it together!

**Comment by irtaza9** [comment]
yesterday I just found that the marquee tag is deprecated by his author. So I checked out different npm packages that provide the functionality of marquee, and you know I find out the best package. I appreciate the efforts of team who is working on it. At the end I want to add myself in this feature request as I am in need of similar functionality. 

I want to use the marquee and inside the marquee I'll map the data.

**Comment by justin-chu** [comment]
Added this in 1.5.0 - however, it's currently experimental and may be buggy. Also note that since I've rotated the child elements, if you want to set the marquee's width and height, just swap the values for vertical marquees.
