### ISSUE TITLE
Need a way to add ref to <div className="marquee-container">

### ISSUE THREAD

**Issue by Github010101011** [justin-chu/react-fast-marquee#44]
I need to add a ref to:

```
<div className="marquee-container ref={ref}>
</div>
```

Is there anyway I can do so? I tried adding it to the <Marquee /> tag but it doesn't appear to work.  This is needed for nextjs image's lazy load: lazyboundary. or the images are loading too slow.

```
<Marquee ref={ref}>
</Marquee>
```

**Comment by justin-chu** [comment]
Added support for this in 1.5.0
