### ISSUE TITLE
Font size inconsistent on iOS (appears fine in development, but differs for live/production)

### ISSUE THREAD

**Issue by AndrewNow** [justin-chu/react-fast-marquee#45]
Hey all,

I'm having an issue styling the font size of the children of my marquee.

The font size doesn't seem to change on the live version of the site, but appears fine locally.

Testing: 
![image](https://user-images.githubusercontent.com/57265008/179424102-fd374627-622e-4c71-925c-7a54c40e0120.png)

Production:
![image](https://user-images.githubusercontent.com/57265008/179424159-5a17c66a-2e9f-4ca3-b3e8-0852fd56f88f.png)

Here's my code:

```js
const BannerMarquee = ({ data }) => {
  return (
    <Wrapper>
      <Marquee gradientWidth={0} speed={55}>
        <small>
          <Link href={`${data.link}`}>{data.title}</Link>
        </small>
      </Marquee>
    </Wrapper>
  );
};

export default BannerMarquee;

const Wrapper = styled.div`
  width: 100%;
  background-color: var(--color-turquoise);
  * {
    font-size: 16px !important;
  }
  small {
    padding: 1rem 0;
  }

  small > a {
    text-decoration: none;
    color: var(--static-black);
  }

  :hover {
    /* cursor: pointer; */
    small > a {
      text-decoration: underline;
    }
  }
  @media (max-width: ${breakpoints.m}px) {
    * {
      font-size: 14px !important;
    }
  }
`;
```

**Comment by givi-phirtskhalava** [comment]
Hi @AndrewNow, had the same issue and this seems to fix it:

`body {
    -webkit-text-size-adjust: 100%;
}`

More on https://stackoverflow.com/a/4966556

**Comment by fallenleavesguy** [comment]
me too.-webkit-text-size-adjust: 100%; fixed it.
