### ISSUE TITLE
Marquee component not displaying; animation not following all the way through

### ISSUE THREAD

**Issue by thadtayo** [justin-chu/react-fast-marquee#46]
There are two main issues I am seeing:

1. Without manually setting a height, the Marquee component does not display. Images below will show that this is because the container has a height of 0.
![image](https://user-images.githubusercontent.com/32399417/180124135-cf54e4d6-711a-4833-a45c-50b8c04e48bf.png)
![image](https://user-images.githubusercontent.com/32399417/180124198-bc6f648a-425a-4e4c-943a-2178a4c3ed96.png)

2. Rather than the text animating all the way to the end (right to left), as soon as the Marquee element hits the left side of the screen, it restarts the animation.

Code to reproduce:
```
import Marquee from "react-fast-marquee"

export default function HeaderAnimation() {
    return (
        <Marquee className='h-screen' gradient={false} speed={250}> // class to make it visible
            <span>THIS SHOULD BE SCROLLING</span>
            <span>THIS SHOULD BE SCROLLING</span>
            <span>THIS SHOULD BE SCROLLING</span>
            <span>THIS SHOULD BE SCROLLING</span>
        </Marquee>
     </div>
    )
}
```

Browsers: Google Chrome and Microsoft Edge both experience these issues

Dependencies:
React: 18.2.0
react-fast-marquee: ^1.3.2

**Comment by justin-chu** [comment]
Sorry, I was unable to reproduce this
