### ISSUE TITLE
Problems Running Marquee with NEXTJS

### ISSUE THREAD

**Issue by danielschmid** [justin-chu/react-fast-marquee#5]
Is there something to consider when using react-fast-marquee within a NEXTJS project. It doesn't work for me and I can't find the error.

**Comment by justin-chu** [comment]
Thanks - I've tested it, and the issue was with Next.js server-side rendering. I've published a patch which disabled server-side rendering for react-fast-marquee, so it should now work with Next.js. Let me know if it's still broken!

**Comment by Lucien950** [comment]
This is still problematic
![image](https://user-images.githubusercontent.com/20777515/142745256-c571bde4-e91f-46ab-89a6-b3457be15f04.png)
