### ISSUE TITLE
gradient color for dark/white mode

### ISSUE THREAD

**Issue by Raqibnur** [justin-chu/react-fast-marquee#55]
Is there a method to dynamically change the gradient colors in the dark and white mode?

**Comment by Wyatt-SG** [comment]
@Raqibnur Yes. You can change the gradient color with the `gradientColor` prop. More on the props here: https://github.com/justin-chu/react-fast-marquee#react-fast-marquee

**Comment by yogyy** [comment]
have you figure it out?

**Comment by justin-chu** [comment]
As @Wyatt-SG mentioned, you can use the `gradientColor` prop to dynamically change the gradient color
