### ISSUE TITLE
[Feature Request] A callback function prop that executes after the marquee has finished rendering

### ISSUE THREAD

**Issue by rubek-joshi** [justin-chu/react-fast-marquee#65]
It would be really nice if there was a callback prop with the name along the lines of `onRenderComplete` or `onRenderFinish` so we can run some logic after the component has been successfully rendered.

An example use case for this would be to [refresh the scroll trigger of the GSAP](https://greensock.com/docs/v3/Plugins/ScrollTrigger/refresh()) library so it can recalculate measurements after the `<Marquee />` component has been rendered.

**Comment by tochibedford** [comment]
@rubek-joshi this issue causes a layout shift which makes Gsap's measurements slight off, correct?
