### ISSUE TITLE
Consider using a string instead of an array for gradientColor

### ISSUE THREAD

**Issue by kcpru** [justin-chu/react-fast-marquee#67]
I noticed that the gradientColor prop in the React component is currently defined as an array [number, number, number]. However, I believe it might be more convenient and flexible to use a string instead. This would allow users to input colors in hex or RGB format.

For example, many popular libraries, like chakra-ui, provide functions such as useColorModeValue for dynamically changing colors. These functions typically return colors as strings, and it would be more convenient to use a similar string representation for the gradientColor prop. This would align with common practices and make it easier for developers to work with the component.

**Comment by justin-chu** [comment]
Thanks for the suggestion, added this in v1.6.1!
