### ISSUE TITLE
Please consider removing !important

### ISSUE THREAD

**Issue by matteomontipo** [justin-chu/react-fast-marquee#74]
Please consider removing !important in its npm css, at least for the `display: flex`
Next.js component level css module doesn't overwrite it not even using !important, I can only by adding both a higher level class + !important but still.. but most importantly inline Tailwind classes can't overwrite that, not even using `!`.
No need to use !important on `.marquee-container `.

**Comment by justin-chu** [comment]
Fixed in v1.6.1!
