### ISSUE TITLE
not working correctly when the dir='rtl' for the page

### ISSUE THREAD

**Issue by shboul1** [justin-chu/react-fast-marquee#79]
when I set the dir for the page to 'rtl' 
strange behavior starts happening

example : 
https://codesandbox.io/s/naughty-alex-w47x88?file=/public/index.html

**Comment by amgadawp** [comment]
@shboul1 did you manage to find a workaround !

**Comment by shboul1** [comment]
Nope :/

**Comment by Moon04** [comment]
i managed to find a workaround
```
<div dir="ltr">
  <Marquee>
     Marquee content
   </Marquee>
</div>
```

**Comment by ZeeshanJafar6356** [comment]
did you find a solution for this?

**Comment by shboul1** [comment]
Yes!

```
import Marquee from 'react-fast-marquee';
import Image from 'next/image';
export default function MarqueeComponent({ lang }: { lang: string }) {
  return (
    <Marquee
      speed={100}
      gradient
      autoFill
      gradientWidth={100}
      style={{
        direction: lang === 'ar' ? 'ltr' : null,
      }}
    >
      {['1', '2', '3', '4', '5', '6', '7'].map((image) => (
        <Image
          key={image}
          className="mx-[60px] w-24 md:w-40"
          src={`/images/partners/${image}.png`}
          alt="ABB"
          width={200}
          height={200}
        />
      ))}
    </Marquee>
  );
}
```

```
.marquee .child {
  display: flex;
  align-items: center;
  justify-content: center;
}
```

**Comment by ZeeshanJafar6356** [comment]
@shboul1 its still not working:
here is my code:
import React, { useState, useEffect } from 'react';
import FastMarquee from 'react-fast-marquee';
import "./MyMarqueeComponent.css"
const Slider = () => {
  const [isPaused, setIsPaused] = useState(false);
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    // Check if viewport width is less than 600px (you can adjust this threshold)
    const handleResize = () => {
      setIsMobile(window.innerWidth < 600);
    };

    handleResize(); // Initial check
    window.addEventListener('resize', handleResize);

    return () => {
      window.removeEventListener('resize', handleResize);
    };
  }, []);

  const handleMouseEnter = () => {
    setIsPaused(true);
  };

  const handleMouseLeave = () => {
    setIsPaused(false);
  };

  return (
    <div className='slider-wrapper'>
      <FastMarquee
        style={{
          width: '100%',
          minHeight: isMobile ? '31px' : '31px', // Adjusted height for mobile
          backgroundColor: '#0dccd7',
          color: '#fff',
          // padding: '10px 0',
          fontWeight:"bold",
          textShadow: '0.5px 0.5px 0.5px rgba(0,0,0,0.3)',
          fontSize: isMobile ? '11px' : '24px', // Adjusted font size for mobile
        }}
        pauseOnHover
        speed={200}
        gradientColor={[255, 255, 255]}
        gradientWidth={50}
        direction="left"
        pause={isPaused}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        className='fast-marquee'
      >
        <div style={{ width: '35px' }}></div>
        <div>
          Hurray! You are in the right place *
          <span style={{ color: '#f3589e', fontWeight: 'bold' }}> 100K+ social media followers </span> *
          We value every customer *
          <span style={{ color: '#f3589e', fontWeight: 'bold' }}> 100% customer satisfaction </span> *
          We guarantee your entry *
          <span style={{ color: '#f3589e', fontWeight: 'bold' }}> SSL certificate website </span> *
          Secured payout *
          <span style={{ color: '#f3589e', fontWeight: 'bold' }}> 24/7 Customer Support </span> *
          If you are not 100% satisfied, we will refund you 100%
        </div>
      </FastMarquee>
    </div>
  );
};

export default Slider;

**Comment by shboul1** [comment]
Can you put it in a codepen or a live editor ?

**Comment by ZeeshanJafar6356** [comment]
@shboul1 on iphone devices its creating this glitch issue when start again
i dont know much about codepen
can you please solve it for me thanks i have to show this today to the client

**Comment by ZeeshanJafar6356** [comment]
@shboul1 brother?

**Comment by moaaz-bhnas** [comment]
Hi everyone,
I found a simle solution. Just wrap the component with a div that always has `dir` attribute set to `ltr`, and control the direction using Marquee's `direction` attribute

``` js
<div dir="ltr">
      <FastMarquee className="bg-black py-1">
        <div className="flex items-center gap-6 pe-6">
          {icons.map((Icon, index) => (
            <Fragment key={index}>
              <GrowByTg />
              <Icon className="w-5 text-white" />
            </Fragment>
          ))}
        </div>
      </FastMarquee>
    </div>
```

**Comment by rehan-taiftec** [comment]
> Hi everyone, I found a simle solution. Just wrap the component with a div that always has `dir` attribute set to `ltr`, and control the direction using Marquee's `direction` attribute
> 
> <div dir="ltr">
>       <FastMarquee className="bg-black py-1">
>         <div className="flex items-center gap-6 pe-6">
>           {icons.map((Icon, index) => (
>             <Fragment key={index}>
>               <GrowByTg />
>               <Icon className="w-5 text-white" />
>             </Fragment>
>           ))}
>         </div>
>       </FastMarquee>
>     </div>

this works for me thanks for saving my time

**Comment by ygg-sanooj** [comment]
@shboul1  There is an issue in the scroll keyframe in rtl direction 
currently the keyframe is 
```
    @keyframes scroll {
      0%{
        transform: translateX(0%);
      }
      100%{
        transform: translateX(-100%);
      }
      
    }
```

it should be 
```
    @keyframes scroll {
      0%{
        transform: translateX(100%);
      }
      100%{
        transform: translateX(0%);
      }
      
    }
```

this works fine in my code
```
.rfm-marquee{
  @include rtl-styles{
    @keyframes arabic-scroll {
      0%{
        transform: translateX(100%);
      }
      100%{
        transform: translateX(0%);
      }
      
    }
    animation: arabic-scroll var(--duration) linear var(--delay) var(--iteration-count);
    animation-play-state: var(--play);
    animation-delay: var(--delay);
    animation-direction: var(--direction);
  }
}
```

**Comment by ZeeshanJafar6356** [comment]
can you please check my code above?

**Comment by ygg-sanooj** [comment]
> can you please check my code above?

Yes, but it's still a bug in the package, right? It would be better if it were handled within the package itself.

**Comment by Minding000** [comment]
I wrote a marquee package that supports `dir` out of the box: https://www.npmjs.com/package/tiny-marquee
