### ISSUE TITLE
Support IE11

### ISSUE THREAD

**Issue by savkelita** [justin-chu/react-fast-marquee#8]
Hi @justin-chu,

First of all great lib, with clean API Doc. 
Are you planning to support IE 11? 

Do you have any temporary solution/suggestion like polyfill or something else?

Thanks.

**Comment by justin-chu** [comment]
Hi @savkelita, thanks for using this library! Unfortunately there are no solutions at the moment, but I will be working on supporting IE 11 in the near future.
