### ISSUE TITLE
I am not able to make the children horizontally aligned, there should be a alignItems property in the props

### ISSUE THREAD

**Issue by mh-jsx** [justin-chu/react-fast-marquee#80]
* Adding Horizontal Alignment

Introduces the alignItems property, enabling horizontal alignment of children within a container.

Current Solution using CSS: 

```
.initial-child-container,
.marquee {
    align-items: center;
}
```

**Comment by mh-jsx** [comment]
The "align-items: center " is already added in the "marquee"class element. But for the "intial-child-container" element, it is missing. That's we see except the intial children the multiplied children or duplicate children are aligned already in center. 

We just need to update the scss for .intial-child-container with 
`align-items: center`
 property

**Comment by justin-chu** [comment]
Added in v1.6.1!
