### ISSUE TITLE
gradient property compatibility issues in Safari browser on Mac

### ISSUE THREAD

**Issue by hsyfee** [justin-chu/react-fast-marquee#90]
After setting the gradient property in the latest version, there is a styling issue with a black shadow in Safari browser on Mac.
Official code is as follows.
`.rfm-overlay::before, .rfm-overlay::after {
  background: linear-gradient(to right, var(--gradient-color), transparent);
}`
But in the Safari browser, the 'transparent' attribute appears as a black transparent shadow. I see that in the old version of RFM, this 'transparent' attribute was not present. In the new version, this 'transparent' attribute cannot be changed, resulting in the above-mentioned issue.

**Comment by justin-chu** [comment]
@semvgelooven sorry, this should now be fixed in 1.6.4!
