### ISSUE TITLE
Gradient is unnatural after v1.6.3

### ISSUE THREAD

**Issue by dninomiya** [justin-chu/react-fast-marquee#99]
This seems to be the case because the gradation does not end with transparency. I think this is logically the correct result.

In my project, there was no problem with v1.6.2.

https://dninomiya.com

and v1.6.3 has issue.

gradientColor="hsl(--var(background))"
<img width="1232" alt="image" src="https://github.com/justin-chu/react-fast-marquee/assets/5842851/9f1cf56d-d2b5-4387-8f2f-afb62777017f">

gradientColor="red"
<img width="1344" alt="image" src="https://github.com/justin-chu/react-fast-marquee/assets/5842851/770fa00f-b466-4407-88a4-658d58e891c6">

**Comment by justin-chu** [comment]
Hi, this should be fixed in 1.6.4
